### ISSUE TITLE
Crash on call to Vk.vkEnumeratePhysicalDevices

### ISSUE THREAD

**Issue by SamHSmith** [jpbruyere/vk.net#7]
Hi, my code crashes when I try to use the Vk.vkEnumeratePhysicalDevices function.
Here is my code:

***
            VkInstance inst = CreateInstance();
            
            uint deviceCount = 0;
            Assert(Vk.vkEnumeratePhysicalDevices(inst, (IntPtr)(&deviceCount), IntPtr.Zero));

            VkPhysicalDevice[] physicalDevices = new VkPhysicalDevice[deviceCount];

            fixed (VkPhysicalDevice* devPtr = &physicalDevices[0])
            {
                Assert(Vk.vkEnumeratePhysicalDevices(inst, (IntPtr)(&deviceCount), (IntPtr)devPtr));
            }

            VkPhysicalDevice physicalDevice = _PickPhysicsDevice(physicalDevices, deviceCount);
***
Am I using the api the correct way? Or else why is it crashing inside of Vk.vkEnumeratePhysicalDevices?

**Comment by jpbruyere** [comment]
I recommend you to check the [PhysicalDeviceCollection](https://gitlab.com/jpbruyere/vke.net/blob/master/vke/src/base/PhysicalDevice.cs#L25) class of [vke.net](https://gitlab.com/jpbruyere/vke.net) to have a working example. Vke.net has several examples inspired from Sacha Willems samples. vke.net is a higher level api using vk.net which is quiet raw to use, Maybe you'll find easier to start programming with that api.

**Comment by jpbruyere** [comment]
I had some trouble for vke.net on github due to git lfs quotas. I've recreated the repo on github and added a download script for the samples datas.

**Comment by SamHSmith** [comment]
I solved the issue and moved on. Cant remember what fixed my issue.
